//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories_sub_categories
    {
        public int id { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> sub_category { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual sub_categories sub_categories { get; set; }
    }
}
