//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookShop.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCon : DbContext
    {
        public dbCon()
            : base("name=dbCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<categories_sub_categories> categories_sub_categories { get; set; }
        public virtual DbSet<cheque> cheques { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<item_variants> item_variants { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<retail_invoice_items> retail_invoice_items { get; set; }
        public virtual DbSet<retail_invoices> retail_invoices { get; set; }
        public virtual DbSet<retail_returns> retail_returns { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sub_categories> sub_categories { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_roles> users_roles { get; set; }
        public virtual DbSet<voucher_sales> voucher_sales { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
        public virtual DbSet<wholesale_invoice_items> wholesale_invoice_items { get; set; }
        public virtual DbSet<wholesale_invoices> wholesale_invoices { get; set; }
    }
}
