//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.item_variants = new ObservableListSource<item_variants>();
            this.retail_invoice_items = new ObservableListSource<retail_invoice_items>();
            this.wholesale_invoice_items = new ObservableListSource<wholesale_invoice_items>();
            this.retail_returns = new ObservableListSource<retail_returns>();
        }
    
        public int id { get; set; }
        public string barcode { get; set; }
        public string description { get; set; }
        public Nullable<decimal> retail_price { get; set; }
        public Nullable<decimal> wholesale_price { get; set; }
        public Nullable<decimal> special_price { get; set; }
        public Nullable<decimal> last_price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> pack_size { get; set; }
        public Nullable<decimal> pack_price { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> sub_category { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual category category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<item_variants> item_variants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<retail_invoice_items> retail_invoice_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<wholesale_invoice_items> wholesale_invoice_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<retail_returns> retail_returns { get; set; }
        public virtual sub_categories sub_categories { get; set; }
    }
}
