//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int id { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<System.DateTime> login_datetime { get; set; }
        public Nullable<System.DateTime> logout_datetime { get; set; }
    
        public virtual user user1 { get; set; }
    }
}
