//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class retail_returns
    {
        public int id { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> relevant_invoice { get; set; }
        public Nullable<int> cashier { get; set; }
        public string status { get; set; }
    
        public virtual item item1 { get; set; }
        public virtual retail_invoices retail_invoices { get; set; }
        public virtual user user { get; set; }
    }
}
