//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher_sales
    {
        public int id { get; set; }
        public Nullable<int> voucher { get; set; }
        public Nullable<int> customer { get; set; }
        public Nullable<int> cashier { get; set; }
        public Nullable<int> date { get; set; }
        public string status { get; set; }
    
        public virtual customer customer1 { get; set; }
        public virtual user user { get; set; }
        public virtual voucher voucher1 { get; set; }
    }
}
