//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBookShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wholesale_invoice_items
    {
        public int id { get; set; }
        public Nullable<int> invoice { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> discount { get; set; }
    
        public virtual item item1 { get; set; }
        public virtual wholesale_invoices wholesale_invoices { get; set; }
    }
}
